title: InterVisions
description: Participatory AI for intersectional bias auditing and benchmarking in vision & language foundation models
theme: just-the-docs

url: https://intervisions.github.io

baseurl: ""

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
